-- Controle de Decisões — Embraer — Quesitos Ergonômicos
-- Rodar no SQL Editor do projeto Supabase "Valores" (sydamnqagkdmczmgkvso)

create table public.embraer_quesitos_ergonomicos (
  id bigint generated by default as identity primary key,
  processo text, reclamante text, prazo_envio date,
  responsavel_sigla text, status text default 'Pendente',
  criado_em timestamptz default now(), concluido_em timestamptz
);
alter table public.embraer_quesitos_ergonomicos enable row level security;
create policy "anon full access" on public.embraer_quesitos_ergonomicos for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_quesitos_ergonomicos;

NOTIFY pgrst, 'reload schema';
