-- Controle de Decisões — Embraer
-- Rodar uma vez no SQL Editor do projeto Supabase "Valores" (sydamnqagkdmczmgkvso)

create table public.reportes_decisao_embraer (
  id bigint generated by default as identity primary key,
  numero_processo text,
  nome_reclamante text,
  responsavel_sigla text,
  advogado_responsavel text,
  advogado_parte_contraria text,

  perito_peri text,
  data_pericia_peri text,
  pericia_dia_adicional text,
  laudo_periculosidade_resultado text,
  laudo_periculosidade_data_inicio date,
  laudo_periculosidade_data_final date,
  laudo_periculosidade_motivo text,
  laudo_periculosidade_detalhamento text,
  laudo_periculosidade_fundamentacao text,
  decisao_periculosidade_igual_laudo text,

  laudo_insalubridade_resultado text,
  laudo_insalubridade_data_inicio date,
  laudo_insalubridade_data_final date,
  laudo_insalubridade_motivo text,
  laudo_insalubridade_detalhamento text,
  laudo_insalubridade_outros text,
  laudo_insalubridade_fundamentacao text,
  decisao_insalubridade_igual_laudo text,

  laudo_ergonomico text,
  perito_medica text,
  data_pericia_medica text,
  medica_doenca text,
  medica_area_corpo text,
  medica_motivos text,
  medica_fonte_informacao text,
  medica_laudo_resultado text,
  medica_fundamentacao text,

  sentenca_resultado text,
  sentenca_data date,
  sentenca_juiz text,
  sentenca_pedidos_deferidos text,
  sentenca_pedidos_indeferidos text,
  sentenca_causa_raiz text,
  sentenca_principal_favoravel text,
  sentenca_principal_desfavoravel text,
  sentenca_obrigacao_fazer text,
  sentenca_embargos text,
  sentenca_reintegracao text,
  sentenca_reintegracao_resultado text,
  sentenca_reintegracao_nota text,
  coisa_julgada text,
  coisa_julgada_resultado text,
  coisa_julgada_motivo text,

  acordao_trt_reclamada text,
  acordao_trt_data date,
  acordao_trt_turma text,
  acordao_trt_relator text,
  acordao_trt_resumo text,
  trt_embargos text,
  recurso_revista_resultado text,
  acordao_tst text,
  acordao_tst_data date,
  acordao_tst_camara text,
  acordao_tst_ministro text,
  acordao_tst_resumo text,
  tst_embargos text,

  execucao text,
  ultima_movimentacao text,
  execucao_resumo text,
  exec_calculo_reclamante_valor numeric,
  exec_calculo_reclamante_data date,
  exec_calculo_reclamada_valor numeric,
  exec_calculo_reclamada_data date,
  exec_pagamento_valor numeric,
  exec_pagamento_data date,
  exec_inss_valor numeric,
  exec_inss_data date,
  exec_garantia_valor numeric,
  exec_garantia_data date,
  exec_custas_valor numeric,
  exec_custas_data date,
  exec_gru_valor numeric,
  exec_gru_data date,
  exec_homologacao_calculos text,
  exec_valor_homologado numeric,
  exec_valor_homologado_data date,
  exec_solicitacao_pagamento text,
  exec_solicitacao_pagamento_data date,

  envio_cliente_laudo text,
  inserir_gerencia_laudo text,
  envio_cliente_sentenca text,
  inserir_gerencia_sentenca text,
  envio_cliente_acordao text,
  inserir_gerencia_acordao text,
  envio_cliente_execucao text,
  inserir_gerencia_execucao text,

  status text default 'Pendente',
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now(),
  concluido_em timestamptz
);

alter table public.reportes_decisao_embraer enable row level security;

create policy "anon full access" on public.reportes_decisao_embraer
  for all
  to anon
  using (true)
  with check (true);

alter publication supabase_realtime add table public.reportes_decisao_embraer;
