-- Controle de Decisões — Embraer — 2ª rodada (7 tabelas novas)
-- Rodar no SQL Editor do projeto Supabase "Valores" (sydamnqagkdmczmgkvso)

-- ===================== REINTEGRADOS =====================
create table public.embraer_reintegrados (
  id bigint generated by default as identity primary key,
  processso_no text, nome_do_reclamante text, tipo_de_processo_rt_ou_ms text, chapa text, vt text,
  juiz text, comarca text, advogado_reclamante text, informar_outros_processos_do_mesmo_reclamante text,
  unidade_embraer text, diretoria text, gerencia text, admissao date, demissao text, distribuicao_da_acao date,
  qual_o_fundamento_do_pedido_de_reintegracao text, se_for_doenca_cct_qual_doenca_alegada text,
  familia_cid text, familia_cid_reintegracao text, quando_alega_ter_adquirido_a_doenca text,
  alega_ter_adquirido_a_doenca_no_periodo_de_vigencia_da_cct text, empregado_reintegrado text,
  data_reintegracao date, a_pericia_medica_ja_ocorreu text, qual_o_resultado_da_pericia_medica text,
  a_pericia_ergonomica_ja_ocorreu text, qual_o_resultado_da_pericia_ergonomica text,
  tem_audiencia_futura_agendada_se_sim_para_quando text, houve_decisao_liminar text,
  houve_pedido_de_reconsideracao_da_decisao_por_parte_da_emb text, houve_mandado_de_seguranca_por_parte_da_embraer text,
  sentenca text, houve_recurso_ordinario_por_parte_da_embraer text, acordao_trt text, acordao_tst text,
  ultima_decisao_reintegracao_deferida_ou_indeferida text, onde_foi_a_ultima_decisao text, status text,
  fase_processual text, risco_do_elaw text, valor_do_risco numeric, valor_da_provisao numeric,
  escritorio_que_preencheu_a_planilha text, analise_objetiva_dos_documentos_apresentados_pelo_reclaman text,
  risco_em_relacao_aos_documentos_apresentados text, analise_das_condicoes_juridicas text,
  risco_em_relacao_as_condicoes_juridicas text, risco_em_relacao_a_analise_comparativa_de_i_a text,
  tempo_provavel_para_a_reintegracao text, probabilidade_de_reintegracao text, obs text, obs_marol text, sigla text,
  criado_em timestamptz default now(), atualizado_em timestamptz default now()
);
alter table public.embraer_reintegrados enable row level security;
create policy "anon full access" on public.embraer_reintegrados for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_reintegrados;

-- ===================== ESTRATÉGICOS =====================
create table public.embraer_estrategicos (
  id bigint generated by default as identity primary key,
  processso_no text, nome_do_reclamante text, tipo_de_processo_rt_ou_ms text, chapa text, vt text, comarca text,
  advogado_reclamante text, informar_outros_processos_do_mesmo_reclamante text, unidade_embraer text,
  vice_presidencia text, diretoria text, gerencia text, admissao date, demissao text, distribuicao_da_acao date,
  grupo_de_objetos text, objetos text, motivo_da_relevancia text, resumo_do_processo_com_enfase_na_relevancia text,
  houve_decisao_liminar text, sentenca text, acordao_trt text, acordao_tst text, status text, fase_processual text,
  risco text, valor_do_risco numeric, valor_da_provisao numeric, escritorio_que_preencheu_a_planilha text,
  obs text, obs_marol text,
  criado_em timestamptz default now(), atualizado_em timestamptz default now()
);
alter table public.embraer_estrategicos enable row level security;
create policy "anon full access" on public.embraer_estrategicos for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_estrategicos;

-- ===================== INSALUBRIDADE E PERICULOSIDADE =====================
create table public.embraer_insalubridade_periculosidade (
  id bigint generated by default as identity primary key,
  processo text, resp_verificar text, responsavel_pela_pasta text, id_elaw text, status text, pasta_p_c text,
  reclamante text, advogado_reclamante text, tipo_de_acao text, grupo_de_objetos text, objetos text, fase text,
  local_dos_autos text, vara text, comarca text, uf text, grupo_empresas text, esfera text, categoria_do_cargo text,
  ultimo_cargo text, risco_prognostico_de_perda text, valor_da_causa numeric, valor_do_risco numeric,
  valor_da_provisao numeric, diferenca numeric, ultima_decisao text, insal_e_peri text, perito_do_juizo text,
  local_da_pericia_planta_abreviada text, data_da_pericia date, local_da_pericia text, laudo_apresentado text,
  data_de_apresentacao_do_laudo date, resultado_do_laudo_geral text, periodo_da_condenacao_de_periculosidade text,
  periodo_da_condenacao_da_insalubridade text, planta text, setores_periciados_unificada text, setores_periciados text,
  ha_pedido_de_periculosidade text, agente_da_periculosidade text, resultado_do_laudo_periculosidade text,
  inflamaveis text, combustivel text, explosivos text, energia_eletrica text, obs_periculosidade text,
  ha_pedido_de_insalubridade text, agente_da_insalubridade text, resultado_do_laudo_insalubridade text,
  grau_de_enquadramento text, agentes_biologicos text, ruido text, qual_area_deu_o_ruido text,
  agentes_quimicos text, solventes text, oleos_e_graxas text, obs_insalubridade text, marol_respostas text,
  criado_em timestamptz default now(), atualizado_em timestamptz default now()
);
alter table public.embraer_insalubridade_periculosidade enable row level security;
create policy "anon full access" on public.embraer_insalubridade_periculosidade for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_insalubridade_periculosidade;

-- ===================== DOENÇAS =====================
create table public.embraer_doencas (
  id bigint generated by default as identity primary key,
  processo text, cid text, familia_cid text, setor text, id_elaw text, status text, pasta_p_c text,
  reclamante text, advogado_reclamante text, tipo_de_acao text, grupo_de_objetos text, objetos text, fase text,
  local_dos_autos text, vara text, comarca text, uf text, empresa text, grupo_de_empresas text, esfera text,
  categoria_do_cargo text, ultimo_cargo text, risco_prognostico_de_perda text, ultima_decisao_do_processo text,
  ultima_decisao_do_laudo text, data_da_pericia_medica date, data_da_pericia_ergonomica date, pericia_medica text,
  pericia_ergonomico text, status_da_pericia_medica text, status_da_pericia_ergnomico text, tipo_de_pericia text,
  perito_medico_do_juizo text, perito_engenheiro_do_juizo text, embraer_conclusao_laudo_ergonomico text,
  embraer_conclusao_laudo_medico text, embraer_conclusao_grau_do_risco_ergonomico text,
  embraer_conclusao_nexo_doenca text, embraer_percentual_de_reducao_da_capacidade text, embraer_tipo_de_doenca text,
  embraer_parte_do_corpo text, tipo_de_doenca_ajustado text, acompanhamento text,
  criado_em timestamptz default now(), atualizado_em timestamptz default now()
);
alter table public.embraer_doencas enable row level security;
create policy "anon full access" on public.embraer_doencas for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_doencas;

-- ===================== SOLICITAÇÃO DE CÁLCULOS (GERAL) =====================
create table public.embraer_solicitacoes_calculos (
  id bigint generated by default as identity primary key,
  numero_processo text, nome_reclamante text, tipo_subsidio text, link_documentos text, prazo_envio date,
  outros_detalhes text, responsavel_sigla text, status text default 'Pendente',
  criado_em timestamptz default now(), concluido_em timestamptz
);
alter table public.embraer_solicitacoes_calculos enable row level security;
create policy "anon full access" on public.embraer_solicitacoes_calculos for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_solicitacoes_calculos;

-- ===================== DETERMINAÇÃO PARA REINTEGRAÇÃO =====================
create table public.embraer_determinacao_reintegracao (
  id bigint generated by default as identity primary key,
  processo text, reclamante text, setor text, telefone_reclamante text, valor_risco numeric, prognostico text,
  prazo_reintegracao date, interesse_acordo text, resultado_laudo text, valor_multa text, fundamentos text,
  outras_obs text, link_pdf text, responsavel_sigla text, status text default 'Pendente',
  criado_em timestamptz default now(), concluido_em timestamptz
);
alter table public.embraer_determinacao_reintegracao enable row level security;
create policy "anon full access" on public.embraer_determinacao_reintegracao for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_determinacao_reintegracao;

-- ===================== AJUSTE DE FASE E PROGNÓSTICO NO ELAW =====================
create table public.embraer_ajuste_fase_prognostico (
  id bigint generated by default as identity primary key,
  advogado_solicitante text, assistente_responsavel text, processo text, reclamante text,
  novo_prognostico text, nova_fase text, observacoes text, status text default 'Pendente',
  criado_em timestamptz default now(), concluido_em timestamptz
);
alter table public.embraer_ajuste_fase_prognostico enable row level security;
create policy "anon full access" on public.embraer_ajuste_fase_prognostico for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_ajuste_fase_prognostico;

NOTIFY pgrst, 'reload schema';
