-- Controle de Decisões — Embraer — Subsídio de Quesitos Médicos
-- Rodar no SQL Editor do projeto Supabase "Valores" (sydamnqagkdmczmgkvso)

create table public.embraer_subsidio_quesitos_medicos (
  id bigint generated by default as identity primary key,
  processo text, reclamante text, id_esclarecimento text, prazo date, link_copia_integral text,
  responsavel_sigla text, status text default 'Pendente',
  criado_em timestamptz default now(), concluido_em timestamptz
);
alter table public.embraer_subsidio_quesitos_medicos enable row level security;
create policy "anon full access" on public.embraer_subsidio_quesitos_medicos for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_subsidio_quesitos_medicos;

NOTIFY pgrst, 'reload schema';
