-- Controle de Decisões — Embraer — Levantamento de Garantia / Devolução de Valor
-- Rodar no SQL Editor do projeto Supabase "Valores" (sydamnqagkdmczmgkvso)

create table public.embraer_levantamento_garantia (
  id bigint generated by default as identity primary key,
  processo text, reclamante text,
  valor_original_deposito numeric, valor_residual_levantar numeric,
  data_pagamento_deposito date, prazo date,
  responsavel_sigla text, status text,
  criado_em timestamptz default now(), concluido_em timestamptz, atualizado_em timestamptz default now()
);
alter table public.embraer_levantamento_garantia enable row level security;
create policy "anon full access" on public.embraer_levantamento_garantia for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_levantamento_garantia;

NOTIFY pgrst, 'reload schema';
