-- Controle de Decisões — Embraer — Minutos Residuais
-- Rodar no SQL Editor do projeto Supabase "Valores" (sydamnqagkdmczmgkvso)
-- Espelha a planilha "P&C - Minutos Residuais.xlsx"

create table public.embraer_minutos_residuais (
  id bigint generated by default as identity primary key,
  numero_processo text, nome_parte_contraria text, ultimo_cargo text, empresa text, comarca text,
  vara_local text, foro_tribunal_orgao text, objeto text, status text, data_distribuicao date,
  fase_processual text, prognostico text, valor_da_causa numeric, provisao numeric, valor_do_risco numeric,
  criado_em timestamptz default now(), atualizado_em timestamptz default now()
);
alter table public.embraer_minutos_residuais enable row level security;
create policy "anon full access" on public.embraer_minutos_residuais for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_minutos_residuais;

NOTIFY pgrst, 'reload schema';
