-- Controle de Decisões — Embraer — Solicitação de Testemunha
-- Rodar no SQL Editor do projeto Supabase "Valores" (sydamnqagkdmczmgkvso)

create table public.embraer_solicitacao_testemunha (
  id bigint generated by default as identity primary key,
  processo text, reclamante text,
  data_audiencia date, horario text,
  tipo_audiencia text, modalidade text, vara text,
  materia_periodo text,
  item3_oitiva text, item4_vistoria text,
  item5_gestor text, item6_outros_processos text,
  item7_testemunha_informada text, item7_link text,
  recomendacao text, observacoes text,
  responsavel_sigla text, status text,
  criado_em timestamptz default now(), concluido_em timestamptz
);
alter table public.embraer_solicitacao_testemunha enable row level security;
create policy "anon full access" on public.embraer_solicitacao_testemunha for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_solicitacao_testemunha;

NOTIFY pgrst, 'reload schema';
