-- Controle de Decisões — Embraer — 3ª rodada (Agendamento de Perícia + Inscrição S.O.)
-- Rodar no SQL Editor do projeto Supabase "Valores" (sydamnqagkdmczmgkvso)

-- ===================== AGENDAMENTO DE PERÍCIA =====================
create table public.embraer_agendamento_pericia (
  id bigint generated by default as identity primary key,
  processo text, reclamante text, tipo_pericia text, data_pericia date, horario text, local_pericia text,
  responsavel_sigla text, status text default 'Pendente',
  criado_em timestamptz default now(), concluido_em timestamptz
);
alter table public.embraer_agendamento_pericia enable row level security;
create policy "anon full access" on public.embraer_agendamento_pericia for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_agendamento_pericia;

-- ===================== INSCRIÇÃO S.O. (SUSTENTAÇÃO ORAL) =====================
create table public.embraer_inscricao_so (
  id bigint generated by default as identity primary key,
  processo text, advogado_inscrever text, assistente_responsavel text, texto_pauta text,
  status text default 'Pendente',
  criado_em timestamptz default now(), concluido_em timestamptz
);
alter table public.embraer_inscricao_so enable row level security;
create policy "anon full access" on public.embraer_inscricao_so for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_inscricao_so;

NOTIFY pgrst, 'reload schema';
