-- Controle de Decisões — Embraer — Encerramentos
-- Rodar no SQL Editor do projeto Supabase "Valores" (sydamnqagkdmczmgkvso)

-- ===================== ENCERRAMENTOS =====================
-- pagamentos: array jsonb de {tipo, valor} (Depósito de Garantia, Depósito Judicial,
-- Execução, Pagamento) — lista livre, quantas linhas o usuário adicionar no formulário.
-- valor_total: soma dos valores de "pagamentos", calculada no cliente e salva aqui
-- pra listar/exportar sem precisar reprocessar o JSON.
create table public.embraer_encerramentos (
  id bigint generated by default as identity primary key,
  processo text, reclamante text, responsavel_sigla text, motivo text,
  pagamentos jsonb default '[]'::jsonb, valor_total numeric,
  observacoes text,
  criado_em timestamptz default now(), atualizado_em timestamptz default now()
);
alter table public.embraer_encerramentos enable row level security;
create policy "anon full access" on public.embraer_encerramentos for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.embraer_encerramentos;

NOTIFY pgrst, 'reload schema';
